- id: doi:10.1111/febs.70031
  image: images/febs.webp

- id: doi:10.1016/j.mib.2024.102494
  image: images/coim-1.png

- id: doi:10.1126/sciadv.adk1887
  image: images/sciadv.svg
  extra-links:
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10558122/
      text: PMC Full Text
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2023.02.15.528712v1
      text: Preprint - bioRxiv
    - type: press
      link: https://www.nature.com/articles/d41586-023-03105-3
      text: Nature Research
    - type: press
      link: https://newsroom.ucla.edu/releases/mice-need-diverse-gut-microbiome-to-form-healthy-placentas
      text: UCLA Newsroom

- id: doi:10.1016/j.chom.2022.08.006
  image: images/chm.svg
- id: doi:10.1016/bs.irn.2022.06.004
  date: 2022-7-9
  image: images/inr.png
- id: doi:10.1016/j.bbr.2021.113353
  image: images/bbr.svg
  extra-links:
    - type: preprint
      link: https://pubmed.ncbi.nlm.nih.gov/33979656/
      text: PMC Full Text
- id: doi:10.1038/s41586-020-2745-3
  image: images/nature.svg
  extra-links:
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7554197/
      text: PMC Full Text
    - type: podcast
      link: https://www.microbe.tv/twin/twin-15/
      text: This Week in Neuroscience, Episode 15
    - type: video
      link: https://www.youtube.com/watch?v=cqfVBVkOS1U
      text: The Sheekey Science Show
    - type: press
      link: https://www.nature.com/articles/d41586-020-02657-y
      text: Nature News and Views
    - type: press
      link: https://www.nature.com/articles/s41583-020-00401-z
      text: Nature Reviews Neuroscience
    - type: press
      link: https://www.sciencenews.org/article/mother-mouse-gut-microbes-microbiome-pup-brain
      text: Science News
    - type: press
      link: https://newsroom.ucla.edu/releases/maternal-microbiota-and-the-fetal-brain
      text: UCLA Newsroom
    - type: press
      link: https://theconversation.com/how-a-pregnant-mouses-microbes-influence-offsprings-brain-development-new-study-offers-clues-146521
      text: The Conversation
- id: doi:10.1177/0022034520908594
  image: images/jdr.svg
  extra-links:
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7243424/
      text: PMC Full Text
    - type: press
      link: https://doi.org/10.1177/0022034520918536
      text: Special Edition on Oral Microbiome
- id: doi:10.1038/s41564-019-0540-4
  image: images/naturemicro.svg
  extra-links:
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6879823/
      text: PMC Full Text
    - type: press
      link: https://www.nature.com/articles/s41575-019-0227-6.pdf?proof=t
      text: Nature Reviews Gastroenterology and Hepatology
- id: doi:10.1016/j.neuron.2018.12.035
  image: images/neuron.svg
  extra-links:
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6661156/
      text: PMC Full Text
- id: doi:10.1016/j.cell.2018.04.027
  image: images/cell.svg
  extra-links:  
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6003870/
      text: PMC Full Text
    - type: press
      link: https://nyti.ms/2CV37me
      text: New York Times
    - type: press
      link: https://science.sciencemag.org/content/360/6394/1199.3
      text: Science
    - type: press
      link: https://stm.sciencemag.org/content/10/446/eaau0471.full?intcmp=trendmd-stm
      text: Science Translational Medicine
    - type: press
      link: https://facultyopinions.com/prime/733283386?bd=1#tab=recommendations
      text: Faculty Opinions
    - type: press
      link: https://goo.gl/snenm5
      text: PNAS Journal Club
    - type: press
      link: https://reader.elsevier.com/reader/sd/pii/S1931312818303263?token=7C607731CE0BBCB54F15D6E6E8645C487C96BBFD2F74D4E3D89698DFA98AF07153A5C3F3F78DE11A0673257238F56E78
      text: Cell Host & Microbe
    - type: press
      link: https://lifesciences.ucla.edu/2018-19-life-sciences-excellence-awards-winners/
      text: UCLA Life Sciences Excellence Award
- id: doi:10.1038/nmicrobiol.2016.122
  image: images/naturemicro.svg
  extra-links:
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6961809/
      text: PMC Full Text
- id: doi:10.1146/annurev-neuro-072116-031347
  image: images/annualreviews.svg
  extra-links:  
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6661159/
      text: PMC Full Text
- id: doi:10.1038/s41386-018-0211-9
  image: images/neuropsycho.svg
  extra-links:  
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6224506/
      text: PMC Full Text
    - type: press
      link: https://www.nature.com/articles/s41591-018-0246-9
      text: Nature Medicine
- id: doi:10.1016/j.biopsych.2016.08.024
  image: images/biopsych.svg
  extra-links:  
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5285286/
      text: PMC Full Text
- id: doi:10.3389/fncel.2020.600777
  image: images/frontiers.svg
  extra-links:  
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7735995/
      text: PMC Full Text
- id: doi:10.1016/j.neuroscience.2015.08.060
  image: images/neuroscience.svg
  extra-links:  
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4603663/
      text: PMC Full Text
- id: doi:10.1007/s11427-013-4493-1
  image: images/scichina.svg
  extra-links:  
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3804076/
      text: PMC Full Text
- id: doi:10.1523/JNEUROSCI.3382-15.2015
  image: images/jneuro.svg
  extra-links:  
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4666919/
      text: PMC Full Text
- id: doi:10.1038/s42003-021-02301-z
  image: images/commbio.svg